name: Log ISS Location Data Daily

on: push
jobs:
  emailcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 22f3002760@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      - name: Commit and push changes
        run: | # shell
          git config --global user.name "athianna"
          git commit -m "successfully done" || exit 0
          git push
      
